#spring.application.name=serv
#server.port=8081
#
##mysql
#spring.datasource.url=jdbc:mysql://localhost:3307/test?serverTimezone=Asia/Seoul
#spring.datasource.username=root
#spring.datasource.password=Justin980120@
##jpa
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring:
    application:
        name: serv
    datasource:
        url: jdbc:mysql://localhost:3307/test?serverTimezone=Asia/Seoul
        username: root
        password: Justin980120@
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect
server:
    port: 8081


